import React from "react"
import Style from "./style.module.scss"
import Image from "../Projects/ProjectImage"

const About = ({ duration, anim, easing }) => {
    return (
        <div className="main__container" id="about">
            <div className="main__container__title">
                <div>
                    <h2
                        data-sal={anim}
                        data-sal-delay={duration}
                        data-sal-easing={easing}
                    >
                        What is Hedwig?
                    </h2>
                </div>
                <div className={Style.about__container}>
                    <div className={Style.about__image}>
                        <div
                            data-sal="fade"
                            data-sal-delay={duration}
                            data-sal-easing={easing}
                        >
                            <Image
                                filename="pngwing.com.png"
                                alt="Hedwig Logo"
                                style={{ width: "20%", height: "120%" }}
                            />
                        </div>
                    </div>
                    <div className={Style.about__text}>
                        <div>
                            <p
                                data-sal={anim}
                                data-sal-delay={duration}
                                data-sal-easing={easing}
                            >
                                <big style={{ fontSize: "30px" }}>
                                    Hedwig - One stop to reduce carbon emission
                                    in tech world
                                </big>
                            </p>
                            <p
                                data-sal={anim}
                                data-sal-delay={duration}
                                data-sal-easing={easing}
                            >
                                Hedwig is a project intended to reduce the
                                carbon footprints generated by electronic
                                gadgets and internet. It consists of several
                                tools designed to reduce the internet usage by a
                                certain computer. They include unsubscription of
                                unwanted mails by user, turning off PC from
                                android phone, compressing files sent by mail so
                                that less data is transferred through internet
                                etc.
                            </p>
                            <p
                                data-sal={anim}
                                data-sal-delay={duration}
                                data-sal-easing={easing}
                            >
                                While thinking about carbon footprints, people
                                only think about carbon emission by vehicles,
                                industries etc. There is also one more source of
                                CO2 emission is to be considered which is
                                emission by internet. The computing industry
                                contributes 2 percent of global carbon
                                emissions, similar to the global aviation
                                industry. Thus, thinking about the carbon
                                footprints by internet is also important.
                            </p>
                        </div>
                        <div
                            data-sal={anim}
                            data-sal-delay={duration}
                            data-sal-easing={easing}
                            className={Style.resume__link}
                        >
                            <a href="http://localhost:5000/">Go to Project</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default About
