# To get the mail unsubscribe list
POST http://localhost:5000/getUnsubscribeList
Content-Type: application/json

{
    "email": "your_email",
    "password": "your_gmail_app_password"
}


# To login to gmail
POST  http://localhost:5000/login
Content-Type: application/json
{
    "email":"your_email",
    "password": "your_gmail_app_password" 
}